//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClass.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Class
    {
        public int ClassId { get; set; }
        public string Name { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        public Nullable<int> StudentIds { get; set; }

        [NotMapped]
        public string Search { get; set; }
        [NotMapped]
        public string SortBy { get; set; }

        [NotMapped]

        public string SortOrder { get; set; }
        [NotMapped]
        public int PageIndex { get; set; }
        [NotMapped]
        public int PageSize { get; set; }
    }
}
