//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentClass.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> ClassIds { get; set; }
        [NotMapped]
        public string Search { get; set; }
        [NotMapped]
        public string SortBy { get; set; }

        [NotMapped]

        public string SortOrder { get; set; }
        [NotMapped]
        public int PageIndex { get; set; }
        [NotMapped]
        public int PageSize { get; set; }

    }
}
